enum ADC_SRC {
  WEEL_LEFT_FIRST = 0,
  WEEL_RIGHT_FIRST,
  WEEL_LEFT_LAST,
  WEEL_RIGHT_LAST,
  COMPRESSOR
};

#define WEEL_LEFT_FIRST_PIN A0
#define WEEL_RIGHT_FIRST_PIN A1
#define WEEL_LEFT_LAST_PIN A2
#define WEEL_RIGHT_LAST_PIN A3
#define COMPRESSOR A4

struct ADC_MAXMIN {
  uint16_t max_v;
  uint16_t min_v;
  ADC_SRC src;
};



